In [2]:
import numpy as np
import random as r
from engine import Tensor
import nn

In [3]:
a = Tensor(np.random.normal(loc=0.0, scale=0.02, size=(10,4)))
print(a)
toks = np.random.randint(10, size=(2,5), dtype="uint8")
print(toks)
b = a[toks]
print(b)

Tensor:
([[-0.02603588 -0.00352715  0.00280701  0.01016098]
 [-0.00721529 -0.01587873 -0.0062522  -0.00072068]
 [-0.00670402 -0.02862454  0.0217753  -0.00042181]
 [ 0.00581642  0.0087818  -0.00090144  0.00745409]
 [ 0.02561187 -0.02296846  0.01869389  0.00101456]
 [ 0.02514433  0.03709546 -0.01621873 -0.04603719]
 [ 0.02596619 -0.00636101  0.01865721 -0.0092996 ]
 [-0.0137553   0.01806812  0.0014459  -0.01559639]
 [-0.00735595 -0.00842719  0.00899819  0.01719298]
 [-0.01022263 -0.00559453 -0.00699819  0.00589717]])
Grad:
([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]])
[[2 7 6 3 1]
 [4 0 4 1 5]]
Tensor:
([[[-0.00670402 -0.02862454  0.0217753  -0.00042181]
  [-0.0137553   0.01806812  0.0014459  -0.01559639]
  [ 0.02596619 -0.00636101  0.01865721 -0.0092996 ]
  [ 0.00581642  0.0087818  -0.00090144  0.00745409]
  [-0.00721529 -0.01587873 -0.0062522  -0.00072068]]

 [[ 0.02561187 -0.0229

In [12]:
toks = np.random.randint(10, size=(2,5)).astype(np.uint8)
E = nn.Embedding(10, 4)
print(E(toks))

Tensor:
([[[ 0.03414191  0.00291135  0.00520161 -0.0065626 ]
  [ 0.00452175 -0.00969068 -0.01035584  0.01223635]
  [ 0.044107   -0.00605651 -0.0001346  -0.01784277]
  [-0.02113504 -0.00568031  0.01881736  0.0057308 ]
  [-0.02113504 -0.00568031  0.01881736  0.0057308 ]]

 [[-0.00453549 -0.02250952 -0.00713876  0.02313512]
  [-0.00021872  0.00175731 -0.03714253 -0.02141185]
  [-0.00453549 -0.02250952 -0.00713876  0.02313512]
  [ 0.044107   -0.00605651 -0.0001346  -0.01784277]
  [-0.02113504 -0.00568031  0.01881736  0.0057308 ]]])
Grad:
([[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]])


In [14]:
toks = np.random.randint(10, size=(2,5)).astype(np.uint32)
print(toks.dtype)

uint32


In [17]:
print(E)

Emedding:
(Tensor:
([[-0.01416529  0.00058155 -0.03188991 -0.01245398]
 [ 0.044107   -0.00605651 -0.0001346  -0.01784277]
 [-0.00453549 -0.02250952 -0.00713876  0.02313512]
 [ 0.03414191  0.00291135  0.00520161 -0.0065626 ]
 [ 0.00452175 -0.00969068 -0.01035584  0.01223635]
 [ 0.01400981  0.02079001  0.0009166   0.01699287]
 [-0.00239151  0.02554203  0.00159429 -0.03229662]
 [-0.02113504 -0.00568031  0.01881736  0.0057308 ]
 [-0.00021872  0.00175731 -0.03714253 -0.02141185]
 [ 0.01296001  0.00322441  0.00045042  0.00999693]])
Grad:
([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]))
