In [3]:
import numpy as np
import random as r
from engine import Tensor

In [17]:
a = Tensor([[1.,2,3],[4,5,6]])
b = a**2
print(a)
print(b)

Tensor:
([[1. 2. 3.]
 [4. 5. 6.]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])
Tensor:
([[ 1.  4.  9.]
 [16. 25. 36.]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])
