In [3]:
import numpy as np
import random as r
from engine import Tensor

In [8]:
a = Tensor([[1.,2,3,4],[5,6,7,8]])
b = a.reshape((2,2,2))
c = b.reshape((8))
print(a)
print(b)
print(c)

Tensor:
([[1. 2. 3. 4.]
 [5. 6. 7. 8.]])
Grad:
([[0. 0. 0. 0.]
 [0. 0. 0. 0.]])
Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]])
Tensor:
([1. 2. 3. 4. 5. 6. 7. 8.])
Grad:
([0. 0. 0. 0. 0. 0. 0. 0.])
