In [2]:
import numpy as np
import random as r
from engine import Tensor
import nn

In [3]:
a = Tensor(np.array([[[1.,2],[3,4]],[[5,6],[7,8]]]), requires_grad=True)
print(a)
m = a.max()[0]
m.backward()
print(m)
print(a)

Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]])
Tensor:
(8.0)
Grad:
(1.0)
Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]])


In [4]:
b = Tensor(np.array([[[1.,2],[3,4]],[[5,6],[7,8]]]), requires_grad=True)
print(b)
m = b.max(0)[0]
m.backward()
print(m)
print(b)

Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]])
Tensor:
([[5. 6.]
 [7. 8.]])
Grad:
([[1. 1.]
 [1. 1.]])
Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]]])


In [5]:
c = Tensor(np.array([[[1.,2],[3,4]],[[5,6],[7,8]]]), requires_grad=True)
print(c)
m = c.max(1)[0]
m.backward()
print(m)
print(c)

Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]])
Tensor:
([[3. 4.]
 [7. 8.]])
Grad:
([[1. 1.]
 [1. 1.]])
Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [1. 1.]]

 [[0. 0.]
  [1. 1.]]])


In [6]:
d = Tensor(np.array([[[1.,2],[3,4]],[[5,6],[7,8]]]), requires_grad=True)
print(d)
m = d.max(2)[0]
m.backward()
print(m)
print(d)

Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]])
Tensor:
([[2. 4.]
 [6. 8.]])
Grad:
([[1. 1.]
 [1. 1.]])
Tensor:
([[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]])
Grad:
([[[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]])
