In [2]:
import numpy as np
import random as r
from engine import Tensor

In [8]:
a = Tensor([[1.,2,3],[4,5,6]])
print(a.softmax(-2))

[4. 5. 6.]
Tensor:
([[-3. -3. -3.]
 [ 0.  0.  0.]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])
Tensor:
([[0.04978707 0.04978707 0.04978707]
 [1.         1.         1.        ]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])
Tensor:
([[1.04978707 1.04978707 1.04978707]
 [1.04978707 1.04978707 1.04978707]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])
Tensor:
([[0.04742587 0.04742587 0.04742587]
 [0.95257413 0.95257413 0.95257413]])
Grad:
([[0. 0. 0.]
 [0. 0. 0.]])


In [6]:
x = Tensor([[[1.,2,3,4],[5,6,7,8],[1,1,2,2]],[[1,-1,1,-1],[1,10,100,1000],[.1,.11,.111,.1111]]])
print(x.softmax())

[[4.000e+00 8.000e+00 2.000e+00]
 [1.000e+00 1.000e+03 1.111e-01]]
Tensor:
([[[-3.00e+00 -2.00e+00 -1.00e+00  0.00e+00]
  [-3.00e+00 -2.00e+00 -1.00e+00  0.00e+00]
  [-1.00e+00 -1.00e+00  0.00e+00  0.00e+00]]

 [[ 0.00e+00 -2.00e+00  0.00e+00 -2.00e+00]
  [-9.99e+02 -9.90e+02 -9.00e+02  0.00e+00]
  [-1.11e-02 -1.10e-03 -1.00e-04  0.00e+00]]])
Grad:
([[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]])
Tensor:
([[[0.04978707 0.13533528 0.36787944 1.        ]
  [0.04978707 0.13533528 0.36787944 1.        ]
  [0.36787944 0.36787944 1.         1.        ]]

 [[1.         0.13533528 1.         0.13533528]
  [0.         0.         0.         1.        ]
  [0.98896138 0.9989006  0.9999     1.        ]]])
Grad:
([[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]])
Tensor:
([[[1.55300179 1.55300179 1.55300179 1.55300179]
  [1.55300179 1.55300179 1.55300179 1.55300179]
  [2.73575888 2.73575888 2.73575