In [1]:
import numpy as np

In [6]:
a = np.array([[0,1],[2,3]])
print(a**2)
print(a*a)
print(a@a)
print(a^2)
print(np.power(a,2))

[[0 1]
 [4 9]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]
[[2 3]
 [0 1]]
[[0 1]
 [4 9]]


In [23]:
b = a > 1
print(b)
c = a * b
print(c)

[[False False]
 [ True  True]]
[[0 0]
 [2 3]]


In [27]:
a = np.exp(-0.2)
print(a)
b = float(a)
print(b)

0.8187307530779818
0.8187307530779818
